services:
  mqtt-to-mongo:
    build: ./mqtt-to-mongo
    container_name: mqtt-to-mongo
    restart: unless-stopped
    env_file: 
      - path: ./.env
      required: true
    depends_on:
      - mongo

  frontend:
    container_name: frontend
    env_file: 
      - path: ./.env
      required: true
    build:
      context: ./meshtextviewer-frontend
      dockerfile: Dockerfile
    ports:
      - 8844:3000

  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    volumes:
      - ./mongodb-data:/data/db
    expose:
      - 27017
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB}

  mongo-express:
    image: mongo-express
    container_name: mongoexpress
    restart: unless-stopped
    ports:
      - ${MONGO_EX_PORT}:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
      ME_CONFIG_BASICAUTH_ENABLED: false